const lengua={
	'cod'				: 'Codigo',
	'name'				: 'Nombre',
	'descrip'			: 'Descripcion',
	'controlRequired'	: 'Es un campo requerido',
	'pass'				:'Password',
	'sts'				:"Estatus",
	'empresa'			:'Empresa',
	'perfil'			:'Perfil',
	'lasing'			:'Ultimo ingreso',
	'Perfil'			:'Perfil',
	'Escunper'			:'Escoja un perfil',
	'Escunuser'			:'Escoja un usuario',
	'CodVen'			:'Codigo del vendedor',
	'Ident'				:'Identidad',
	'Dir'				:'Direccion',
	'User'				:'Usuario',
	'coVini'			:'Valor de inicio',
	'coVfin'			:'Valor final',
	'coAct'				:'Valor actual',
	'coFeV'				:'fecha emision',
	'coFeI'				:'fecha limite',
	'coFfin'			:'fecha final',
	'CAI'				:'CAI',
	'Pref'				:'Prefijo',
	'Descrip'			:'Descripcion',
	'Movil'				:'Movil',
	'fecCre'			:'Fecha de creacion',
	'corr'				:'Correlativo',
	'Tel'				:'Telefono',
	'Zona'				:'Zona',
	'Ruta'				:'Ruta',
	'RTN'				:'RTN',
	'codCli'			:'Codigo del cliente',
	'tipo'				:'Tipo',
	'Ubi'				:'Ubicacion',
	'Dispon'			:'Disponible',
	'Bod'				:'Bodega',
	'Vehic'				:'Vehiculo',
	'Ven'				:'Vendedor',
	'Unid'				:'Unidades',
	'SubPrecio'			:'Precio',
	'SubCant'			:'Cantidad',
	'DiasAv'			:'Dias habiles',
	'HoraPr'			:'Horas preferidas',
	'Obser'				:'observacion',
	'Cli'				:'Cliente',
	'Produc'			:'Producto',
	'CantActual'		:'Cantidad actual',
	'CantidadT'			:'Cantidad transferir',
	'ListPro'			:'Lista de productos',
	'ListBod'			:'Lista de bodegas',
	'proBodAct'			:'Producto en la actual bodega',
	'proBodSel'			:'Cantidad del producto seleccionado',
	'NoSuPro'			:'No hay suficiente producto',
	'ProArti'			:'Producto/Articulo',
	'Familia'			:'Familia',
	'sudProd'			:'Producto que lo compone',
	'gruCl'				:'Clave',
	'gruTi'				:'Tipo',
	'gruDe'				:'Descripcion'

};
export default lengua;


			